extends: 
  - "standard-react"
env:
  browser: true
  jest: true
  node: true
plugins:
  - "react"
parser: babel-eslint
rules:
  semi: [2, always]
  indent: [error, 4, { SwitchCase: 1 }]
  arrow-parens: [2, as-needed]
  no-var: 2
  no-param-reassign: [2, {
      props: false
  }]
  object-curly-spacing:
    - "error"
    - "always"
  no-else-return: 1
  default-case: 2
  consistent-return: 2
  no-shadow: 2
  no-use-before-define: [error, { functions: false, classes: true }]
  object-property-newline: off
  react/jsx-space-before-closing: 0
  react/sort-prop-types: 1
  react/jsx-key: 1
  react/jsx-handler-names: 1
  react/sort-comp: 1
  react/jsx-sort-props: 1
  react/jsx-indent:
    - 1
    - 4
  react/jsx-indent-props:
    - 1
    - 4